# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      ignore: gh-pages
      only:  master

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - "06:65:7b:06:e7:c3:ec:08:7b:60:6a:02:df:e8:31:9d"

      # run
      - run: npx gitbook install && npx gitbook build
      - run: git checkout gh-pages
      - run: git pull
      - run: cp -R _book/* .
      - run: git clean -fx node_modules
      - run: git clean -fx _book
      - run: git add .
      - run: git commit -a -m "Update docs"
      - run: git push origin gh-pages --force

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          branches:
            only: master
